# Generated by Django 5.0.1 on 2024-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
